services:
  backend:
    container_name: tadaa-backend
    build:
      context: ./backend-nestjs
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_DEV_MODE: ${JWT_DEV_MODE}
      PORT: 3001
      NODE_ENV: development
    volumes:
      - ./backend-nestjs/:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    container_name: tadaa-frontend
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_URL: http://localhost:3001
      INTERNAL_API_URL: http://backend:3001
      NODE_ENV: development
    volumes:
      - ./frontend-nextjs:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: "postgres:16"
    container_name: tadaa-postgres-db
    environment:
      - POSTGRES_USER=max_power
      - POSTGRES_PASSWORD=super-secret
      - POSTGRES_DB=tadaa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
