services:
  backend:
    container_name: tadaa-backend
    build:
      context: ./backend-nestjs
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_DEV_MODE: ${JWT_DEV_MODE}
      PORT: 3001
      NODE_ENV: development
      # HAS_LOKAL_DB: false
    volumes:
      - ./backend-nestjs/:/app
      - /app/node_modules

  frontend:
    container_name: tadaa-frontend
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      PUBLIC_API_URL: http://localhost:3001
      INTERNAL_API_URL: http://backend:3001
      NODE_ENV: development
    volumes:
      - ./frontend-nextjs:/app
      - /app/node_modules
    depends_on:
      - backend
