name: Deploy to mini-pc-wichtel

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend-nestjs
          file: ./backend-nestjs/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend-nextjs
          file: ./frontend-nextjs/Dockerfile.prod
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
          build-args: |
            NEXT_PUBLIC_API_URL=/api

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env file
        run: |
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "OPENAI_API_KEY={{ secrets.OPENAI_API_KEY }}" >> .env
          echo "IMAGE_REPO=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> .env
          echo "FRONTEND_URLS=https://tadaa-events.com" >> .env
          echo "CLOUDFLARE_TOKEN=${{ secrets.CLOUDFLARE_TOKEN }}" >> .env
          # beim zweiten deployment dringend lÃ¶schen
          # oder besser noch migration richtig einrichten!
          echo "DB_SYNC=true" >> .env

      - name: Start Containers
        run: |
          docker compose -f compose.prod.yml pull
          docker compose -f compose.prod.yml up -d
          docker image prune -f
