name: CI (Build & Test)

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        apps: [frontend-nextjs, backend-nestjs]
        node-version: [24]

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: install dependencies
        run: npm ci

      - name: build dependencies
        run: npm run build -w @tadaa/shared

      # machen wir sp√§ter
      # - name: lint
      #   run: npm run lint

      # baut beide apps parallel
      - name: build ${{ matrix.apps}}
        run: npm run build -w ${{matrix.apps}}

      # Optional: sobald wir Tests haben
      # - name: run tests
      #   run: npm run test
