name: CI (Build & Test)

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend-nextjs, backend-nestjs]
        node-version: [24]

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      - name: install dependencies (${{ matrix.service }})
        working-directory: ./${{ matrix.service }}
        run: npm ci

      # machen wir sp√§ter
      # - name: lint
      #   run: npm run lint

      # baut beide apps parallel
      - name: build ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: npm run build

      # Optional: sobald wir Tests haben
      # - name: run tests
      #   run: npm run test
